[[mgr.prepend_keymap]]
on = ["m"]
run = "plugin bookmarks save"
desc = "Bookmark: save current directory"

[[mgr.prepend_keymap]]
on = ["'"]
run = "plugin bookmarks jump"
desc = "Bookmark: jump"

[[mgr.prepend_keymap]]
on = ["b"]
run = "plugin bookmarks delete"
desc = "Bookmark: delete one"

[[mgr.prepend_keymap]]
on = ["B"]
run = "plugin bookmarks delete_all"
desc = "Bookmark: delete all"

